# Generated by Django 6.1.1 on 2026-10-07 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('program_type', models.CharField(choices=[('live_conversation', 'Live Conversation'), ('webinar', 'Webinar'), ('workshop', 'Workshop'), ('discussion', 'Discussion'), ('other', 'Other')], db_index=True, default='live_conversation', max_length=50)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=100)),
                ('zoom_enabled', models.BooleanField(default=False)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=255)),
                ('zoom_passcode', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-scheduled_start', '-created_at'],
            },
        ),
    ]
