/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AmbassadorsRouteImport } from './routes/ambassadors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as JoinRouteImport } from './routes/join'
import { Route as PartnersRouteImport } from './routes/partners'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsRoute = AmbassadorsRouteImport.update({
  id: '/ambassadors',
  path: '/ambassadors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/contact': typeof ContactRoute
  '/conversation': typeof ConversationRoute
  '/join': typeof JoinRoute
  '/partners': typeof PartnersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/contact': typeof ContactRoute
  '/conversation': typeof ConversationRoute
  '/join': typeof JoinRoute
  '/partners': typeof PartnersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ambassadors': typeof AmbassadorsRoute
  '/contact': typeof ContactRoute
  '/conversation': typeof ConversationRoute
  '/join': typeof JoinRoute
  '/partners': typeof PartnersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ambassadors'
    | '/contact'
    | '/conversation'
    | '/join'
    | '/partners'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ambassadors'
    | '/contact'
    | '/conversation'
    | '/join'
    | '/partners'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ambassadors'
    | '/contact'
    | '/conversation'
    | '/join'
    | '/partners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AmbassadorsRoute: typeof AmbassadorsRoute
  ContactRoute: typeof ContactRoute
  ConversationRoute: typeof ConversationRoute
  JoinRoute: typeof JoinRoute
  PartnersRoute: typeof PartnersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors': {
      id: '/ambassadors'
      path: '/ambassadors'
      fullPath: '/ambassadors'
      preLoaderRoute: typeof AmbassadorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AmbassadorsRoute: AmbassadorsRoute,
  ContactRoute: ContactRoute,
  ConversationRoute: ConversationRoute,
  JoinRoute: JoinRoute,
  PartnersRoute: PartnersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
