# Generated by Django 6.1.1 on 2026-10-07 22:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('article', 'Article & Perspectives'), ('report', 'Reports & Publications'), ('public_resource', 'Public Resources'), ('institutional_news', 'Institutional News')], db_index=True, default='article', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('cover_image', models.URLField(blank=True, help_text='URL to the resource cover image')),
                ('external_url', models.URLField(blank=True, help_text='Link to external document or resource')),
                ('author_name', models.CharField(blank=True, help_text='Display name for the author', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
