import { LayoutDashboard, MessageSquare, Users, Handshake, Network, UserPlus } from "lucide-react";

export const TABS = [
  { id: "all", label: "All Submissions", icon: LayoutDashboard },
  { id: "contact", label: "Contact", icon: MessageSquare },
  { id: "join", label: "Join the Conversation", icon: Users },
  { id: "partners", label: "Partners", icon: Handshake },
  { id: "conversation", label: "Apply to Speak", icon: Network },
  { id: "ambassadors", label: "Ambassadors", icon: UserPlus },
];

export const FORM_SCHEMAS: Record<string, { name: string, label: string, type: string, options?: string[] }[]> = {
  contact: [
    { name: "fullName", label: "Full Name", type: "text" },
    { name: "email", label: "Email Address", type: "email" },
    { name: "whatsapp", label: "WhatsApp Number", type: "text" },
    { name: "subject", label: "Subject", type: "text" },
    { name: "message", label: "Message", type: "textarea" },
  ],
  join: [
    { name: "fullName", label: "Full Name", type: "text" },
    { name: "country", label: "Country of Residence", type: "text" },
    { name: "email", label: "Email Address", type: "email" },
    { name: "whatsapp", label: "WhatsApp Number", type: "text" },
    { name: "occupation", label: "Occupation", type: "text" },
    { name: "referral", label: "How did you hear about us", type: "text" },
    { name: "ambassadorReferral", label: "Ambassador / Mobilizer Referral", type: "text" },
    { name: "theme", label: "Theme", type: "text" },
    { name: "message", label: "Message", type: "textarea" },
  ],
  partners: [
    { name: "orgName", label: "Organization Name", type: "text" },
    { name: "orgType", label: "Organization Type", type: "select", options: ["NGO", "University", "Research Institution", "Professional Association", "Youth Organization", "Community Organization", "International Organization", "Other"] },
    { name: "countryReg", label: "Country of Registration", type: "text" },
    { name: "regions", label: "Regions of Operation", type: "text" },
    { name: "contactName", label: "Contact Person Full Name", type: "text" },
    { name: "contactRole", label: "Contact Role", type: "text" },
    { name: "contactEmail", label: "Contact Email", type: "email" },
    { name: "contactWhatsapp", label: "Contact WhatsApp", type: "text" },
    { name: "website", label: "Website", type: "url" },
    { name: "instagram", label: "Instagram Handle", type: "text" },
    { name: "twitter", label: "Twitter / X Handle", type: "text" },
    { name: "linkedin", label: "LinkedIn Page URL", type: "url" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "heardAbout", label: "How did you hear about us?", type: "text" },
    { name: "contribution", label: "Contribution", type: "textarea" },
    { name: "speaking", label: "Speaking Opportunity", type: "select", options: ["Yes", "No"] },
    { name: "additional", label: "Additional Info", type: "textarea" },
  ],
  conversation: [
    { name: "fullName", label: "Full Name", type: "text" },
    { name: "country", label: "Country of Residence", type: "text" },
    { name: "whatsapp", label: "WhatsApp Number", type: "text" },
    { name: "email", label: "Email Address", type: "email" },
    { name: "background", label: "Professional Background", type: "textarea" },
    { name: "title", label: "Proposed Title", type: "text" },
    { name: "theme", label: "Theme", type: "text" },
    { name: "format", label: "Format", type: "text" },
    { name: "abstract", label: "Abstract", type: "textarea" },
    { name: "panelSuggestions", label: "Panel Co-panelist Suggestions", type: "textarea" },
    { name: "why", label: "Why This Topic Matters", type: "textarea" },
    { name: "instagram", label: "Instagram Handle", type: "text" },
    { name: "twitter", label: "Twitter / X Handle", type: "text" },
    { name: "linkedin", label: "LinkedIn Profile URL", type: "url" },
  ],
  ambassadors: [
    { name: "fullName", label: "Full Name", type: "text" },
    { name: "country", label: "Country of Residence", type: "text" },
    { name: "city", label: "City", type: "text" },
    { name: "email", label: "Email Address", type: "email" },
    { name: "whatsapp", label: "WhatsApp Number", type: "text" },
    { name: "instagram", label: "Instagram Handle", type: "text" },
    { name: "twitter", label: "Twitter / X Handle", type: "text" },
    { name: "linkedin", label: "LinkedIn Profile URL", type: "url" },
    { name: "occupation", label: "Current Occupation", type: "text" },
    { name: "why", label: "Why become an Ambassador?", type: "textarea" },
    { name: "promote", label: "How will you promote?", type: "textarea" },
    { name: "meaning", label: "What does mental health mean to you?", type: "textarea" },
    { name: "reach", label: "Estimated Reach", type: "select", options: ["Under 500", "500 to 2000", "2000 to 10000", "Over 10000"] },
    { name: "prior", label: "Prior Advocacy?", type: "select", options: ["Yes", "No"] },
    { name: "priorDetails", label: "Prior Advocacy Details", type: "textarea" },
  ]
};
